Minor changes in sd preparation and sending payload
nh-server/switch-guide pull request #158
Opened 2021-06-03 19:52 UTC by JeffVi

**SD Preparation**

Fixed issue with the note in step 4 being considered as step 5
Added a note about replacing files (for the bootloader folder merge)

*see https://jeffvi.github.io/switch-guide/user_guide/emummc/sd_preparation/*

**Sending a payload (emummc)**

Using the TE payload to check if the switch is patched for more consistency with the rest of the guide. Any reason not to do it?
Also added precision about the hekate payload since the question is frequently asked.

**Sending a payload (syscfw)**

Added precision about the hekate payload since the question is frequently asked.

Not much, but a lot of questions in switch assistance were about that these days.
For TE instead of Hekate to check if the device is patched, feel free to close the PR if there is any reason not to do it. I should have asked earlier.

2021-06-18 09:43 UTC, suchmememanyskill commented on docs/user_guide/emummc/sd_preparation.md
> +          - If you're asked to merge the bootloader folders and replace files, do so
`*and* replace files`? You should probably make that `or replace the files`. This should be done for the sysmmc guide as well in the pr

2021-06-18 09:44 UTC, suchmememanyskill commented on docs/user_guide/emummc/sending_payload.md
> +    If your console's screen remains black after you've sent TegraExplorer, it's possible your payload was corrupted, or that your console is patched. If your payload injector program shows that 0 by
Probably worth specifying that not specifically only tegraexplorer works for this, but any payload, like `Tegraexplorer (or any other payload)`

2021-06-18 16:46 UTC, suchmememanyskill approved these changes

2021-06-19 20:34 UTC, el-emmo approved these changes

2021-06-19 22:33 UTC, noirscape requested changes
Missing a few punctuation dots, fix those, then its "looks good to me".

2021-06-19 22:33 UTC, noirscape commented on docs/user_guide/sysnand/sd_preparation.md
> +          - If you're asked to merge the bootloader folders or replace the files, do so
Needs a dot here.

2021-06-19 22:33 UTC, noirscape commented on docs/user_guide/emummc/sd_preparation.md
> +          - If you're asked to merge the bootloader folders or replace the files, do so
Needs a dot here.

2021-06-20 18:24 UTC, noirscape approved these changes

2021-06-20 18:49 UTC, merged