Checkpoint -> JKSV
nh-server/switch-guide pull request #166
Opened 2021-09-10 13:22 UTC by el-emmo

2021-09-10 13:54 UTC, JeffVi requested changes
Just being annoying
Otherwise looks good

2021-09-10 13:54 UTC, JeffVi commented on docs/about.md
> +	- **J-D-K** for [JKSV](https://github.com/J-D-K/JKSV).
Not sure about the indentation here

2021-09-10 13:54 UTC, JeffVi commented on docs/extras/save_management.md
> +Please read Checkpoint's [homepage](https://github.com/SciresM/Checkpoint#usage) for information on how to use it.
Probably want to change the link to "https://github.com/SciresM/Checkpoint" to match with the "homepage" name

2021-09-10 23:44 UTC, suchmememanyskill commented on docs/extras/save_management.md
> +[Checkpoint](https://github.com/SciresM/Checkpoint/releases/tag/ams-19-compat) is also a save manager. It can be used to back up and restore game saves to your SD card. It also has the ability to sha
I do not think we should just wildly link scires' release on our docs page. Maybe mention that the current release is broken, and that there's a semi-fixed build [here]?

2021-09-25 09:10 UTC, suchmememanyskill approved these changes

2021-09-25 12:18 UTC, merged